<?php 
/**
 * Implementation of hook_init().
 */
function community_customizations_init(){
  drupal_add_js(drupal_get_path('module', 'community_customizations') . '/js/community_customizations.js');
  drupal_add_css(drupal_get_path('module', 'community_customizations') . '/css/community.css');
}

/**
 * Implementation of hook_nodeapi().
 */
function community_customizations_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
      global $user;
      if ($user->uid != 0 && $node->type == 'dataset') {
        drupal_add_js(drupal_get_path('module', 'community_customizations') . '/js/community_customizations_suggest.js');
      }
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function community_customizations_menu() {
  $items = array();
  
  $items['community_suggest/form'] = array(
      'page callback' => 'community_customization_suggest_form_callback_ahah',
      'type' => MENU_CALLBACK,
      'access callback' => '_node_add_access',
  );
  
  return $items;
}

function community_customization_suggest_form_callback_ahah() {
  module_load_include('inc', 'node', 'node.pages');  
  $node_type = 'community_suggestion';
  global $user;
  // create a blank node
  $node = array(
      'uid' => $user->uid,
      'name' => (isset($user->name) ? $user->name : ''),
      'type' => $node_type
  );
  
  // Invoke hook_nodapi and hook_node
  node_object_prepare($node);
  
  $output['html'] = drupal_get_js() . drupal_get_form('community_suggestion_node_form', $node);
  if($_GET['html'])
    echo $output['html'];
  else
    drupal_json($output);
}
